"""Deferred-eval decode: ONE lazy graph per token + on-GPU remap + cold-redo.

The next decode-hot lever on top of the fixed hot-set (``test_nemotron_runner_
fixed_hotset.py``). The synced fixed path is token-exact but still does ~one
``mx.eval`` PER MoE layer (to read routed ids for a Python residency check and a
numpy global->slot remap), serialising the GPU ~49x/token on the real 550B.

The deferred path removes every per-layer eval:

* **On-GPU remap** — instead of ``np.asarray(inds)`` + numpy gather, the gate
  wrapper returns ``local = mx.take(g2s, inds)`` LAZILY (no eval, no numpy);
  scores pass through unchanged. The native ``SwitchMLP`` then gathers ``local``
  from the prebuilt fixed stack. The whole 108-layer forward composes into ONE
  graph, evaluated once at ``lm_head``.
* **Optimistic + cold-redo** — a residency miss can't be Python-checked without a
  sync, so the gate also accumulates a LAZY cold flag (did any layer route to a
  non-resident expert?). ONE eval at end-of-token reads it alongside the argmax.
  If cold, the optimistic forward is invalid -> restore the cache snapshot and
  REDO the token via the proven-exact synced fixed path.

The hard gate is TOKEN-EXACTNESS. All-resident token: the on-GPU ``mx.take``
yields the SAME local slots the numpy remap would, so the forward is bit-
identical to the synced fixed path (already proven == stock == page). Cold token:
the optimistic forward is discarded and the token regenerated by the exact path.
So the output == stock for EVERY token, on BOTH fixtures, both branches.
"""
from __future__ import annotations

import tempfile
import unittest

from tests.fixtures.tiny_nemotron import (
    build_tiny_nemotron,
    build_tiny_nemotron_quantized,
)
from tests.test_nemotron_runner_fixed_hotset import (
    MOE_LAYERS,
    PROMPT,
    ROUTED_UNION,
    _stock_greedy,
    _stock_logits,
)


def _count_evals():
    """Patch ``mlx.core.eval`` to tally calls; returns (counter, restore).

    The deferred path's whole point is collapsing ~per-MoE-layer evals into ~1-2
    per token, so the proof is an honest call count of ``mx.eval`` itself.
    """
    import mlx.core as mx

    original = mx.eval
    counter = {"calls": 0}

    def counting(*args, **kwargs):
        counter["calls"] += 1
        return original(*args, **kwargs)

    mx.eval = counting

    def restore() -> None:
        mx.eval = original

    return counter, restore


class NemotronDeferredExactnessTests(unittest.TestCase):
    """Deferred decode == stock == synced-fixed, both fixtures, both branches."""

    def test_deferred_all_resident_logits_exact_both_fixtures(self) -> None:
        """One-shot deferred logits with a COVERING fixed set == stock == synced.

        Override the fixed set to a non-sorted superset of the routed union so
        every MoE layer is all-resident -> pure deferred (no redo). The on-GPU
        ``mx.take`` remap must reproduce the synced numpy remap bit-for-bit.
        """
        import mlx.core as mx

        from smarttensor.adapters.mlx import NemotronHStreamingForwardRunner

        cover = {layer: [7, 2, 5, 1] for layer in MOE_LAYERS}

        for builder in (build_tiny_nemotron, build_tiny_nemotron_quantized):
            with self.subTest(fixture=builder.__name__):
                with tempfile.TemporaryDirectory() as d:
                    path = builder(d)
                    stock = _stock_logits(path, PROMPT)

                    # Synced fixed path (the proven-exact reference).
                    synced = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=4,
                    )
                    self.addCleanup(synced.close)
                    synced.build_fixed_hotset(PROMPT, override=cover)
                    synced_logits = synced.forward_logits(PROMPT)
                    mx.eval(synced_logits)

                    # Deferred path.
                    deferred = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=4,
                    )
                    self.addCleanup(deferred.close)
                    deferred.build_fixed_hotset(PROMPT, override=cover)
                    got = deferred.forward_logits_deferred(PROMPT)
                    mx.eval(got)

                    self.assertEqual(tuple(got.shape), tuple(stock.shape))
                    self.assertEqual(
                        float(mx.max(mx.abs(got.astype(mx.float32) - stock.astype(mx.float32)))),
                        0.0,
                        "deferred all-resident logits diverged from stock",
                    )
                    self.assertEqual(
                        float(mx.max(mx.abs(got.astype(mx.float32) - synced_logits.astype(mx.float32)))),
                        0.0,
                        "deferred all-resident logits diverged from synced fixed",
                    )
                    # Pure deferred: no cold redo fired.
                    self.assertEqual(deferred._deferred_stats["cold_redos"], 0)
                    self.assertGreater(deferred._deferred_stats["deferred_tokens"], 0)

    def test_deferred_all_resident_greedy_exact_both_fixtures(self) -> None:
        """Multi-token deferred greedy with a COVERING fixed set == stock == synced."""
        from smarttensor.adapters.mlx import NemotronHStreamingForwardRunner

        steps = 8
        cover = {layer: [7, 2, 5, 1] for layer in MOE_LAYERS}

        for builder in (build_tiny_nemotron, build_tiny_nemotron_quantized):
            with self.subTest(fixture=builder.__name__):
                with tempfile.TemporaryDirectory() as d:
                    path = builder(d)
                    stock = _stock_greedy(path, PROMPT, steps)

                    synced = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=4,
                    )
                    self.addCleanup(synced.close)
                    synced.build_fixed_hotset(PROMPT, override=cover)
                    synced_tokens = synced.generate_greedy(PROMPT, steps)["tokens"]

                    deferred = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=4,
                    )
                    self.addCleanup(deferred.close)
                    deferred.build_fixed_hotset(PROMPT, override=cover)
                    out = deferred.generate_greedy_deferred(PROMPT, steps)
                    deferred_tokens = out["tokens"]

                    self.assertEqual(
                        deferred_tokens, stock, "deferred decode diverged from stock"
                    )
                    self.assertEqual(
                        deferred_tokens,
                        synced_tokens,
                        "deferred decode diverged from synced fixed",
                    )
                    self.assertEqual(out["cold_redos"], 0)

    def test_deferred_cold_redo_logits_exact_both_fixtures(self) -> None:
        """A MISSING routed expert -> cold detected -> redo -> still == stock == synced.

        Override the fixed set to {2,5} while the layer routes to {2,5,7}: expert
        7 is not resident. The optimistic deferred forward gathers a clamped wrong
        row, the end-of-token cold flag fires, and the token is regenerated by the
        exact synced path. The committed logits must be bit-identical to stock.
        """
        import mlx.core as mx

        from smarttensor.adapters.mlx import NemotronHStreamingForwardRunner

        miss = {layer: [2, 5] for layer in MOE_LAYERS}

        for builder in (build_tiny_nemotron, build_tiny_nemotron_quantized):
            with self.subTest(fixture=builder.__name__):
                with tempfile.TemporaryDirectory() as d:
                    path = builder(d)
                    stock = _stock_logits(path, PROMPT)

                    synced = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=2,
                    )
                    self.addCleanup(synced.close)
                    synced.build_fixed_hotset(PROMPT, override=miss)
                    synced_logits = synced.forward_logits(PROMPT)
                    mx.eval(synced_logits)

                    deferred = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=2,
                    )
                    self.addCleanup(deferred.close)
                    deferred.build_fixed_hotset(PROMPT, override=miss)
                    got = deferred.forward_logits_deferred(PROMPT)
                    mx.eval(got)

                    self.assertEqual(
                        float(mx.max(mx.abs(got.astype(mx.float32) - stock.astype(mx.float32)))),
                        0.0,
                        "deferred cold-redo logits diverged from stock",
                    )
                    self.assertEqual(
                        float(mx.max(mx.abs(got.astype(mx.float32) - synced_logits.astype(mx.float32)))),
                        0.0,
                        "deferred cold-redo logits diverged from synced fixed",
                    )
                    # The cold path was actually taken (the forward was redone).
                    self.assertGreater(deferred._deferred_stats["cold_redos"], 0)

    def test_deferred_cold_redo_greedy_exact_both_fixtures(self) -> None:
        """Multi-token greedy with a MISSING routed expert -> redo every token == stock."""
        from smarttensor.adapters.mlx import NemotronHStreamingForwardRunner

        steps = 8
        miss = {layer: [2, 5] for layer in MOE_LAYERS}

        for builder in (build_tiny_nemotron, build_tiny_nemotron_quantized):
            with self.subTest(fixture=builder.__name__):
                with tempfile.TemporaryDirectory() as d:
                    path = builder(d)
                    stock = _stock_greedy(path, PROMPT, steps)

                    synced = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=2,
                    )
                    self.addCleanup(synced.close)
                    synced.build_fixed_hotset(PROMPT, override=miss)
                    synced_tokens = synced.generate_greedy(PROMPT, steps)["tokens"]

                    deferred = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=2,
                    )
                    self.addCleanup(deferred.close)
                    deferred.build_fixed_hotset(PROMPT, override=miss)
                    out = deferred.generate_greedy_deferred(PROMPT, steps)

                    self.assertEqual(
                        out["tokens"], stock, "deferred cold-redo decode diverged from stock"
                    )
                    self.assertEqual(
                        out["tokens"],
                        synced_tokens,
                        "deferred cold-redo decode diverged from synced fixed",
                    )
                    # Every decode token had a cold layer -> a redo per decode step.
                    self.assertGreater(out["cold_redos"], 0)

    def test_deferred_mixed_native_and_cold_is_exact(self) -> None:
        """One layer all-resident + the other cold in the SAME token -> redo == stock.

        Layer 1 covers ({2,5,7,1}); layer 4 misses 7. A single cold layer makes the
        whole token cold -> redo via the synced path (which itself runs layer 1
        native + layer 4 page). Output still bit-identical to stock and synced.
        """
        from smarttensor.adapters.mlx import NemotronHStreamingForwardRunner

        mixed = {1: [7, 2, 5, 1], 4: [2, 5]}
        steps = 6
        for builder in (build_tiny_nemotron, build_tiny_nemotron_quantized):
            with self.subTest(fixture=builder.__name__):
                with tempfile.TemporaryDirectory() as d:
                    path = builder(d)
                    stock = _stock_greedy(path, PROMPT, steps)

                    synced = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=4,
                    )
                    self.addCleanup(synced.close)
                    synced.build_fixed_hotset(PROMPT, override=mixed)
                    synced_tokens = synced.generate_greedy(PROMPT, steps)["tokens"]

                    deferred = NemotronHStreamingForwardRunner(
                        str(path),
                        pin_policy="all",
                        page_experts=True,
                        fixed_hotset_experts=4,
                    )
                    self.addCleanup(deferred.close)
                    deferred.build_fixed_hotset(PROMPT, override=mixed)
                    out = deferred.generate_greedy_deferred(PROMPT, steps)

                    self.assertEqual(out["tokens"], stock)
                    self.assertEqual(out["tokens"], synced_tokens)
                    self.assertGreater(out["cold_redos"], 0)


class NemotronDeferredEvalCountTests(unittest.TestCase):
    """The deferred all-resident path does FAR fewer evals than the synced path."""

    def test_deferred_does_far_fewer_evals_per_token(self) -> None:
        """Per decode token: deferred ~1-2 evals; synced ~one PER MoE layer.

        The toy has 2 MoE layers, so the synced fixed path evals at least twice
        per token (one ``mx.eval(inds)`` per MoE layer) plus the argmax. The
        deferred path must collapse to a small constant (target ~1-2): no
        per-layer eval at all.
        """
        from smarttensor.adapters.mlx import NemotronHStreamingForwardRunner

        steps = 6
        cover = {layer: [7, 2, 5, 1] for layer in MOE_LAYERS}
        with tempfile.TemporaryDirectory() as d:
            path = build_tiny_nemotron(d)

            # --- Synced fixed path eval count (one decode token).
            synced = NemotronHStreamingForwardRunner(
                str(path),
                pin_policy="all",
                page_experts=True,
                fixed_hotset_experts=4,
            )
            self.addCleanup(synced.close)
            synced.build_fixed_hotset(PROMPT, override=cover)
            # Warm prefill OUTSIDE the counter (we measure steady-state decode).
            synced.generate_greedy(PROMPT, 1)
            counter, restore = _count_evals()
            try:
                synced._decode_one_token_synced(PROMPT)
            finally:
                restore()
            synced_evals = counter["calls"]

            # --- Deferred path eval count (one decode token).
            deferred = NemotronHStreamingForwardRunner(
                str(path),
                pin_policy="all",
                page_experts=True,
                fixed_hotset_experts=4,
            )
            self.addCleanup(deferred.close)
            deferred.build_fixed_hotset(PROMPT, override=cover)
            deferred.generate_greedy_deferred(PROMPT, 1)
            counter, restore = _count_evals()
            try:
                deferred._decode_one_token_deferred(PROMPT)
            finally:
                restore()
            deferred_evals = counter["calls"]

            # The synced path pays at least one eval per MoE layer (2 here).
            self.assertGreaterEqual(
                synced_evals,
                len(MOE_LAYERS),
                "synced fixed path should eval at least once per MoE layer",
            )
            # The deferred path collapses to a small constant, strictly fewer than
            # the synced per-layer cost (and bounded by ~1-2: the single end-of-
            # token flag+argmax eval).
            self.assertLess(
                deferred_evals,
                synced_evals,
                f"deferred ({deferred_evals}) not fewer than synced ({synced_evals})",
            )
            self.assertLessEqual(
                deferred_evals,
                2,
                f"deferred path did {deferred_evals} evals (target ~1-2)",
            )


class NemotronDeferredDefaultPathTests(unittest.TestCase):
    """The deferred path is fully opt-in; default decode is untouched."""

    def test_frequency_built_deferred_is_exact(self) -> None:
        """A frequency-built (no override) deferred decode is exact and pure-deferred."""
        from smarttensor.adapters.mlx import NemotronHStreamingForwardRunner

        steps = 8
        with tempfile.TemporaryDirectory() as d:
            path = build_tiny_nemotron_quantized(d)
            stock = _stock_greedy(path, PROMPT, steps)

            deferred = NemotronHStreamingForwardRunner(
                str(path),
                pin_policy="all",
                page_experts=True,
                fixed_hotset_experts=3,  # == |{2,5,7}|, covers the union
            )
            self.addCleanup(deferred.close)
            built = deferred.build_fixed_hotset(PROMPT, warmup_tokens=8)
            for layer in MOE_LAYERS:
                self.assertEqual(set(built[layer]["order"]), ROUTED_UNION)

            out = deferred.generate_greedy_deferred(PROMPT, steps)
            self.assertEqual(
                out["tokens"], stock, "frequency-built deferred decode diverged from stock"
            )
            self.assertEqual(out["cold_redos"], 0)

    def test_deferred_requires_fixed_hotset(self) -> None:
        """``generate_greedy_deferred`` without a built hot-set raises (opt-in)."""
        from smarttensor.adapters.mlx import NemotronHStreamingForwardRunner

        with tempfile.TemporaryDirectory() as d:
            path = build_tiny_nemotron(d)
            runner = NemotronHStreamingForwardRunner(
                str(path), pin_policy="all", page_experts=True
            )
            self.addCleanup(runner.close)
            with self.assertRaises(Exception):
                runner.generate_greedy_deferred(PROMPT, 4)


if __name__ == "__main__":
    unittest.main()
