#!/bin/bash
# run the serial engine on both nodes: run2.sh [extra args...]
set -e
cd /home/urtho/dev/_experiments/ai/tensorfold
rsync -a --exclude .venv --exclude .git --exclude notes/ref --exclude out --exclude __pycache__ --exclude .claude ./ aiai:tensorfold/
rsync -a --exclude .venv --exclude .git --exclude notes/ref --exclude out --exclude __pycache__ --exclude .claude ./ aiai2:tensorfold/
# leftover ranks of a killed run hold memory and the rendezvous port
for h in aiai aiai2; do timeout 30 ssh $h "docker exec tf-dev pkill -f 'tools/dsv41_' ; true" >/dev/null 2>&1; done
sleep 3
# TF_DUAL=1: both PCIe halves of the 200G port (second half: 10.43.0.1/.2 in NM profile cx7-companion-mtu)
if [ "${TF_DUAL:-0}" = 1 ]; then H0="=roceP2p1s0f0,rocep1s0f0"; H1="=roceP2p1s0f1,rocep1s0f1"; else H0=roceP2p1s0f0; H1=roceP2p1s0f1; fi
NSYS=""; [ -n "${TF_NSYS:-}" ] && NSYS="nsys profile -o /tf/nsys_step -f true --capture-range=cudaProfilerApi --cuda-graph-trace=node --trace=cuda"
# no fixed GID index: the index of a port's RoCE v2 IPv4 GID moves (3 or 4, per device) when an address is re-added
# under a live connection; NCCL picks it per device by version and family, the RoCE all-gather by type and address.
# NCCL_IB_GID_INDEX=N in the caller's environment still pins it.
GIDENV="-e NCCL_IB_ROCE_VERSION_NUM=2 -e NCCL_IB_ADDR_FAMILY=AF_INET -e NCCL_IB_ADDR_RANGE=${NCCL_IB_ADDR_RANGE:-10.42.0.0/15}"
[ -n "${NCCL_IB_GID_INDEX:-}" ] && GIDENV="$GIDENV -e NCCL_IB_GID_INDEX=$NCCL_IB_GID_INDEX"
M=/models/dsv41/DeepSeek-V4.1-Flash-EXL3-2.9bpw; G=/models/dsv41/DeepSeek-V4.1-Flash-engram
timeout 30 ssh aiai2 "docker exec -d -e NCCL_SOCKET_IFNAME=enP2p1s0f1np1 -e NCCL_IB_HCA=$H1 $GIDENV -e NCCL_DEBUG=ERROR -e NCCL_PROTO=${NCCL_PROTO:-} -e TF_PAR=${TF_PAR:-1} -e TF_CARVEOUT=${TF_CARVEOUT:-} -e TF_DSV41_KV_FP8=${TF_DSV41_KV_FP8:-} -e TF_DSV41_KV=${TF_DSV41_KV:-} -e TF_DSV41_IQ_FP4=${TF_DSV41_IQ_FP4:-} -e TF_DSV41_SWA_FP8=${TF_DSV41_SWA_FP8:-} -e TF_DSV41_COMP_BF16=${TF_DSV41_COMP_BF16:-} -e PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-} -e TF_ROUTE_STATS=${TF_ROUTE_STATS:-} -e TF_ZB=${TF_ZB:-121,101} -e TF_ROUND_PROF=${TF_ROUND_PROF:-} -e TF_STEP_THREADS=${TF_STEP_THREADS:-16} -e TF_SKIP_READS=${TF_SKIP_READS:-} -e TF_SPLIT_READS=${TF_SPLIT_READS:-} -e TF_SKIP_SHARED=${TF_SKIP_SHARED:-} -e TF_FOLD_SHARED=${TF_FOLD_SHARED:-} -e TF_ROUTER_SLICES=${TF_ROUTER_SLICES:-} -e TF_L2_PREFETCH=${TF_L2_PREFETCH:-} -e TF_FUSE_HC_DECODE=${TF_FUSE_HC_DECODE:-} -e TF_SUBPROF=${TF_SUBPROF:-} -e TF_GROUPED_WO_A=${TF_GROUPED_WO_A:-} -e TF_MQA_CHUNK=${TF_MQA_CHUNK:-} -e TF_EXL3_ROT_FUSE=${TF_EXL3_ROT_FUSE:-} -e TF_PF_WOA=${TF_PF_WOA:-} -e TF_PF_PROGRAMS=${TF_PF_PROGRAMS:-} -e TF_COPY_DRAFTS=${TF_COPY_DRAFTS:-} -e TF_COPY_MAX=${TF_COPY_MAX:-} -e TF_COMM=${TF_COMM:-} -e TF_RDMA_MAX_KB=${TF_RDMA_MAX_KB:-} -e TF_ONE_GRAPH=${TF_ONE_GRAPH:-} -e TF_DSV41_SHARED_POOL=${TF_DSV41_SHARED_POOL:-} -e TF_DSV41_POOL_TOKENS=${TF_DSV41_POOL_TOKENS:-} -e TF_DSV41_KEPT_ENTRIES=${TF_DSV41_KEPT_ENTRIES:-} -e TF_DSV41_KEEP_MIN=${TF_DSV41_KEEP_MIN:-} -e TF_DSV41_POOL_KEEP=${TF_DSV41_POOL_KEEP:-} -e TF_DSV41_GROW_AHEAD=${TF_DSV41_GROW_AHEAD:-} -e TF_CHUNK_PREFILL=${TF_CHUNK_PREFILL:-} -e TF_DSV41_FAST_TOPK=${TF_DSV41_FAST_TOPK:-} -e TF_DSV41_PREPARED=${TF_DSV41_PREPARED:-} -e TF_EXPERT_LOADS=${TF_EXPERT_LOADS:-} -e TF_EXPERT_LOADS_CFG=${TF_EXPERT_LOADS_CFG:-} -e TF_TAIL_TEST=${TF_TAIL_TEST:-} -e TF_DSV41_BOUNDED_TAIL=${TF_DSV41_BOUNDED_TAIL:-} -e NUMPY_MADVISE_HUGEPAGE=0 -e TF_DSV41_WIDTHS=${TF_DSV41_WIDTHS:-} -e TF_DSV41_SHARED_GRAPHS=${TF_DSV41_SHARED_GRAPHS:-} -e TF_NSYS=${TF_NSYS:-} -e TF_DECODE_PROF=${TF_DECODE_PROF:-} -e TF_DSV41_CUDA_MQA=${TF_DSV41_CUDA_MQA:-} -e TF_DSV41_SHARED_IK=${TF_DSV41_SHARED_IK:-} -e TF_DSV41_MQA_GROUP=${TF_DSV41_MQA_GROUP:-} -e TF_DSV41_MQA_FEW=${TF_DSV41_MQA_FEW:-} -e TF_DECODE_ROWS=${TF_DECODE_ROWS:-} -e TF_PROF_AT=${TF_PROF_AT:-} -e TF_STUDY_TIE=${TF_STUDY_TIE:-} -e TF_DSV41_SELECT_ONCE=${TF_DSV41_SELECT_ONCE:-} -e TF_DSV41_SEG_ROWS=${TF_DSV41_SEG_ROWS:-} -e TF_DSV41_FULL_DEQ=${TF_DSV41_FULL_DEQ:-} -e TF_DSV41_FULL_DEQ_MIB=${TF_DSV41_FULL_DEQ_MIB:-} -e NCCL_ALGO=${NCCL_ALGO:-} tf-dev bash -c 'cd /tf && python tools/dsv41_serial_run.py $M $G --rank 1 --master 10.42.0.1 $* > /tf/serial-r1.log 2>&1'"
timeout 3000 ssh aiai "docker exec -e NCCL_SOCKET_IFNAME=enP2p1s0f0np0 -e NCCL_IB_HCA=$H0 $GIDENV -e NCCL_DEBUG=ERROR -e NCCL_PROTO=${NCCL_PROTO:-} -e TF_PAR=${TF_PAR:-1} -e TF_CARVEOUT=${TF_CARVEOUT:-} -e TF_DSV41_KV_FP8=${TF_DSV41_KV_FP8:-} -e TF_DSV41_KV=${TF_DSV41_KV:-} -e TF_DSV41_IQ_FP4=${TF_DSV41_IQ_FP4:-} -e TF_DSV41_SWA_FP8=${TF_DSV41_SWA_FP8:-} -e TF_DSV41_COMP_BF16=${TF_DSV41_COMP_BF16:-} -e PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-} -e TF_ROUTE_STATS=${TF_ROUTE_STATS:-} -e TF_ZB=${TF_ZB:-121,101} -e TF_ROUND_PROF=${TF_ROUND_PROF:-} -e TF_STEP_THREADS=${TF_STEP_THREADS:-16} -e TF_SKIP_READS=${TF_SKIP_READS:-} -e TF_SPLIT_READS=${TF_SPLIT_READS:-} -e TF_SKIP_SHARED=${TF_SKIP_SHARED:-} -e TF_FOLD_SHARED=${TF_FOLD_SHARED:-} -e TF_ROUTER_SLICES=${TF_ROUTER_SLICES:-} -e TF_L2_PREFETCH=${TF_L2_PREFETCH:-} -e TF_FUSE_HC_DECODE=${TF_FUSE_HC_DECODE:-} -e TF_SUBPROF=${TF_SUBPROF:-} -e TF_GROUPED_WO_A=${TF_GROUPED_WO_A:-} -e TF_MQA_CHUNK=${TF_MQA_CHUNK:-} -e TF_EXL3_ROT_FUSE=${TF_EXL3_ROT_FUSE:-} -e TF_PF_WOA=${TF_PF_WOA:-} -e TF_PF_PROGRAMS=${TF_PF_PROGRAMS:-} -e TF_COPY_DRAFTS=${TF_COPY_DRAFTS:-} -e TF_COPY_MAX=${TF_COPY_MAX:-} -e TF_COMM=${TF_COMM:-} -e TF_RDMA_MAX_KB=${TF_RDMA_MAX_KB:-} -e TF_ONE_GRAPH=${TF_ONE_GRAPH:-} -e TF_DSV41_SHARED_POOL=${TF_DSV41_SHARED_POOL:-} -e TF_DSV41_POOL_TOKENS=${TF_DSV41_POOL_TOKENS:-} -e TF_DSV41_KEPT_ENTRIES=${TF_DSV41_KEPT_ENTRIES:-} -e TF_DSV41_KEEP_MIN=${TF_DSV41_KEEP_MIN:-} -e TF_DSV41_POOL_KEEP=${TF_DSV41_POOL_KEEP:-} -e TF_DSV41_GROW_AHEAD=${TF_DSV41_GROW_AHEAD:-} -e TF_CHUNK_PREFILL=${TF_CHUNK_PREFILL:-} -e TF_DSV41_FAST_TOPK=${TF_DSV41_FAST_TOPK:-} -e TF_DSV41_PREPARED=${TF_DSV41_PREPARED:-} -e TF_EXPERT_LOADS=${TF_EXPERT_LOADS:-} -e TF_EXPERT_LOADS_CFG=${TF_EXPERT_LOADS_CFG:-} -e TF_TAIL_TEST=${TF_TAIL_TEST:-} -e TF_DSV41_BOUNDED_TAIL=${TF_DSV41_BOUNDED_TAIL:-} -e NUMPY_MADVISE_HUGEPAGE=0 -e TF_DSV41_WIDTHS=${TF_DSV41_WIDTHS:-} -e TF_DSV41_SHARED_GRAPHS=${TF_DSV41_SHARED_GRAPHS:-} -e TF_NSYS=${TF_NSYS:-} -e TF_DECODE_PROF=${TF_DECODE_PROF:-} -e TF_DSV41_CUDA_MQA=${TF_DSV41_CUDA_MQA:-} -e TF_DSV41_SHARED_IK=${TF_DSV41_SHARED_IK:-} -e TF_DSV41_MQA_GROUP=${TF_DSV41_MQA_GROUP:-} -e TF_DSV41_MQA_FEW=${TF_DSV41_MQA_FEW:-} -e TF_DECODE_ROWS=${TF_DECODE_ROWS:-} -e TF_PROF_AT=${TF_PROF_AT:-} -e TF_STUDY_TIE=${TF_STUDY_TIE:-} -e TF_DSV41_SELECT_ONCE=${TF_DSV41_SELECT_ONCE:-} -e TF_DSV41_SEG_ROWS=${TF_DSV41_SEG_ROWS:-} -e TF_DSV41_FULL_DEQ=${TF_DSV41_FULL_DEQ:-} -e TF_DSV41_FULL_DEQ_MIB=${TF_DSV41_FULL_DEQ_MIB:-} -e NCCL_ALGO=${NCCL_ALGO:-} tf-dev bash -c 'cd /tf && $NSYS python tools/dsv41_serial_run.py $M $G --rank 0 --master 10.42.0.1 $* 2>&1 | grep -v -E \"Warning|USDT\"'" | tail -n ${TF_TAIL_LINES:-70}
echo "--- rank 1 tail"; timeout 20 ssh aiai2 'tail -4 ~/tensorfold/serial-r1.log'
